### PR TITLE
AMP-50876 Fix type errors in Ampli JS codegen

### PR DESCRIPTION
**Pull request by falconandy**

### CODE REVIEW

**Review by justin-fiedler — CHANGES_REQUESTED** [review]
I'm seeing this error in browser/javascript/react-app/src/App.js
image

**Comment by falconandy** [comment]
@justin-fiedler I do not see that error (WebStorm 2022.1 EAP). I did saw it but I changed `{Config}` to `{Object}` to fix it:
https://github.com/amplitude/ampli-examples/pull/68/files#diff-9f1e0002cc67eef4cd70e9197dec8895fdae3d8bd5496ed0bc0098cf308748ebL67

**Comment by justin-fiedler** [comment]
> @justin-fiedler I do not see that error (WebStorm 2022.1 EAP). I did saw it but I changed `{Config}` to `{Object}` to fix it: https://github.com/amplitude/ampli-examples/pull/68/files#diff-9f1e0002cc67eef4cd70e9197dec8895fdae3d8bd5496ed0bc0098cf308748ebL67

Hmm, this error is still showing for me. I noticed some inconsistency in LoadClientOptions and made a new ticket 
https://amplitude.atlassian.net/browse/AMP-51141

image

**Review by justin-fiedler — APPROVED** [review]
Much better thank you @falconandy

**Review by justin-fiedler — APPROVED** [review]

**Pull request merged**
